### ISSUE TITLE
Importing css files from app.css

### ISSUE THREAD

**Issue by vasconita** [jeffjewiss/ember-cli-postcss#13]
I'm trying to use this plugin but I can´t. I'm sure there is something I'm missing, but I prefer to share it, because maybe there are more people having same problem.

What I'm trying to do is very simple: I have a css of a component (inside styles folder, I realized [pods are not working](https://github.com/jeffjewiss/ember-cli-postcss/issues/11) for the moment) and an import statement in my _app.css_

File: _my-ember-app/app/styles/app.css_
```css
@import './templates/components/widgets/external/analytics-widget.css';
```

File: _my-ember-app/app/styles/templates/components/widgets/external/analytics-widget.css_
```css
.analytics-widget-container{
  animation-name: example-animation;
  animation-duration: 2s;
  animation-iteration-count: infinite;
}

@keyframes example-animation {
  0% {background-color: red;}
  33% {background-color: green;}
  66% {background-color: blue;}
  100% {background-color: red;}
}
```

Then, when I start ember server or directly make a build, the css is not bundled inside assets/my-ember-app.css, because import hasn't been resolved, so it's looking for _my-ember-app/app/styles/templates/components/widgets/external/analytics-widget.css_ in runtime.

Am I doing something wrong? I understood plugin should bundle all my referenced css by imports starting at app.css.
